/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlgorithmsLowerBoundRouteImport } from './routes/algorithms/lower-bound'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsLowerBoundRoute = AlgorithmsLowerBoundRouteImport.update({
  id: '/algorithms/lower-bound',
  path: '/algorithms/lower-bound',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algorithms/lower-bound': typeof AlgorithmsLowerBoundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algorithms/lower-bound': typeof AlgorithmsLowerBoundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algorithms/lower-bound': typeof AlgorithmsLowerBoundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/algorithms/lower-bound'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/algorithms/lower-bound'
  id: '__root__' | '/' | '/algorithms/lower-bound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgorithmsLowerBoundRoute: typeof AlgorithmsLowerBoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/lower-bound': {
      id: '/algorithms/lower-bound'
      path: '/algorithms/lower-bound'
      fullPath: '/algorithms/lower-bound'
      preLoaderRoute: typeof AlgorithmsLowerBoundRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgorithmsLowerBoundRoute: AlgorithmsLowerBoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
